baseURL = 'https://blog.yellowday.day/'
languageCode = 'en-us'
title = "Yisheng's Blog"
theme = 'nostyle'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  favicon = "/favicon.png"
  [params.theme_config]
    back_home_text = ".."
    isShowFooter = true
  [params.taxonomy]
    showCount = true
    showDescription = true

[taxonomies]
  category = "categories"
  tag = "tags"